### ISSUE TITLE
关于hit-oslab实验环境问题请教

### ISSUE THREAD

**Issue by steverao** [DeathKing/Hit-DataStructure-On-Scheme#3]
首先，感谢楼主提供的环境资源分享。但是现在我的64位环境采用make编译linux-0.11出现了as86:Command not found的问题，所以在此处想请教一下楼主该如何解决，谢谢啦！

**Comment by DeathKing** [comment]
@steverao 原项目是基于Ubuntu 16.04 的。推荐使用[实验楼](https://www.shiyanlou.com/courses/115)提供的环境。

**Comment by steverao** [comment]
哦哦，就是感觉实验楼环境操作不便才想着自搭环境的




在2019年10月14日 08:51，DeathKing 写道：

@steverao 原项目是基于Ubuntu 16.04 的。推荐使用实验楼提供的环境。
